spacelift-io/spacelift-policies-example-library

README.md, access/engineering-team-access.rego, access/protect-administrative-stacks.rego, access/slack-channel-access.rego, access/who-when-where-access-restrictions.rego, approval/allowlist-task-commands.rego, approval/multi-team-required-approvals.rego, approval/task-and-run-approvals.rego, approval/two-approvals-no-rejections.rego, login/devops-are-admins.rego, login/external-contributor-access.rego, login/rewriting-user-teams.rego, login/who-when-where-login-restrictions.rego, plan/dont-allow-resource-type.rego, plan/enforce-password-length.rego, plan/enforce-tags-on-resources.rego, plan/infracost-monthly-cost-restriction.rego, push/cancel-in-progress-runs.rego, push/create-proposed-run-from-env-pr-labels.rego, push/ignore-changes-outside-root.rego, push/terragrunt-monorepo-ignore-changes-outside-root.rego, trigger/automated-retries.rego, trigger/trigger-dependencies.rego
* 2 new access policies
* 3 new approval policies
* 1 new push policy
* 1 new trigger policy
* Small consistency updates to existing policies
* Updates to root readme table (adding new policies, and also added a brief description for each policy type)
=> FEATURE - Adds many new policy examples, updates root readme

.github/workflows/continuous-integration.yaml
PR #13 missed a couple of commands that needed to be updated 🤦‍♂️
=> Bump OPA version to v0.44.0 (Missed commands)

README.md, notification/drift-detection-with-changes.rego, notification/drift-detection-with-changes_test.rego
=> notification section policy with drift detection changes policy

README.md, plan/enforce-terraform-version-list.rego, plan/enforce-terraform-version-list_test.rego
=> terraform version list

README.md, approval/approval-outside-working-hours.rego, approval/approval-outside-working-hours_test.rego
=> approval needed outside working hours

README.md, push/lock-button-pauses-runs-by-pushes.rego, push/lock-button-pauses-runs-by-pushes_test.rego
=> locked button paused runs by push events

README.md, notification/slack-channels-with-labels.rego, notification/slack-channels-with-labels_test.rego
=> slack channels set with labels

approval/role-based-approval_test.rego, approval/task-and-run-approvals_test.rego, approval/two-approvals-no-rejections_test.rego, approval/two-approvals-two-rejections_test.rego
=> tests for approval policies

README.md, push/pr-comment-driven-user.rego, push/pr-comment-driven-user_test.rego
=> new push policy for only allowed users to use pr comment driven actions

README.md, login/readers-writers-admins-teams.rego, login/readers-writers-admins-teams_test.rego
=> login policy with teams

README.md, plan/mandatory-and-acceptable-labels-stack.rego, plan/mandatory-and-acceptable-labels-stack_test.rego
=> Stacklabels

login/readers-writers-admins-teams.rego, login/readers-writers-admins-teams_test.rego
=> updated policy with regal

approval/allowlist-task-commands.rego, approval/allowlist-task-commands_test.rego
=> test for allowlist tasks

access/downgrade-access-after-hours.yml
Add metadata for policy examples.
=> Add metadata proposal for policy example

login/external-contributor-access-github.yml
=> add meta for External Contributor Access - GitHub

plan/ensure-resource-creation-before-deletion.yml, plan/require-human-review-for-update-deletion.yml
=> add missing templates for few plan policies

push/allow-forks.rego, push/allow-forks_test.rego, push/create-proposed-run-from-env-pr-labels.rego, push/create-proposed-run-from-env-pr-labels_test.rego, push/deploy-with-git-tag.rego, push/deploy-with-git-tag_test.rego, push/deploy-with-pr-label.rego, push/deploy-with-pr-label_test.rego, push/pr-comment-driven-actions.rego, push/pr-comment-driven-actions_test.rego, push/prs-only.rego, push/prs-only_test.rego, push/set-head-commit-no-trigger.rego, push/set-head-commit-no-trigger_test.rego, push/terragrunt-monorepo-ignore-changes-outside-root.rego, push/terragrunt-monorepo-ignore-changes-outside-root_test.rego
=> unit tests for push policies

.regal/config.yaml, plan/check-blast-radius_test.rego, plan/checkov-failed-checks_test.rego, plan/deny-proposed-runs-warn-track-runs_test.rego, plan/dont-allow-resource-type_test.rego, plan/enforce-cloud-provider_test.rego, plan/enforce-module-use-policy_test.rego, plan/enforce-password-length_test.rego, plan/enforce-tags-on-resources_test.rego, plan/ensure-resource-creation-before-deletion_test.rego, plan/infracost-monthly-cost-restriction_test.rego, plan/kics-severity-counter_test.rego, plan/require-human-review-for-drift-detection-reconciliation_test.rego, plan/require-human-review-for-unreachable-ansible-hosts_test.rego, plan/require-human-review-for-update-deletion_test.rego, plan/require-reasonable-commit-size_test.rego, plan/terrascan-violated-policies_test.rego, plan/tfsec-high-severity-issues_test.rego, plan/trusted-engineers-bypass-review_test.rego
Adding unit tests for plan policies.
=> Add unit tests for plan policies

plan/trivy-high-severity-issues.rego, plan/trivy-high-severity-issues.yml, plan/trivy-high-severity-issues_test.rego
=> Added trivy plan policy

.github/workflows/continuous-integration.yaml, .regal/config.yaml
=> update opa version to what's running in prod which is version 0.64.0

notification/pull-request-comment-summary.rego, notification/pull-request-comment-summary.yml, notification/pull-request-comment-summary_test.rego
=> updated example summary comment with additional badges and tests

trigger/trigger-dependencies-via-labels.yml
The metadata file pointed to a different file than it should.
=> fix: trigger-dependencies-via-labels.yml source

go.mod
=> Relax required Go version

examples/plan/infracost-monthly-cost-restriction.rego, examples/plan/infracost-monthly-cost-restriction_test.rego
In the samples, I noticed there is a `third_party_metadata.custom.object`, so we would need to update the policy accordingly.
Ref: https://docs.spacelift.io/concepts/policy/terraform-plan-policy.html#example-exposing-terraform-configuration-to-the-plan-policy 
=> fix: infracost policy
